### PR TITLE
fix running tests on travis

### PR DESCRIPTION
**Pull request by deric**
- support Ruby 1.9
- extend testing suite

### CODE REVIEW

**Comment by Envek** [comment]
Well, seems like it's not fixed: all tests failed with

```
Evaluation Error: Unknown variable: 'postgresql::repo::version'. at /home/travis/build/Envek/puppet-pgtune/spec/fixtures/modules/pgtune/manifests/init.pp:124:6 
```

Main trouble is that some configuration of [postgresql](https://github.com/puppetlabs/puppetlabs-postgresql) module should be done and some facts should be set in tests. But I still don't know what exactly should be done.

I already asked question at https://github.com/rodjek/rspec-puppet/issues/415 but still have not chance to dig into it. May be it help you.

Thank you for your help! It's appreciated.

**Comment by Envek** [comment]
Try to just rebase it. May be it's fixed after merge of #2

**Comment by deric** [comment]
I've added some default facts and installing dependencies via Librarian. The tests could be still improved but in here I tried just to fix testing pipeline. 

The RSpec `pre_condition` seems to be a good way for testing such dependency. Thanks for the link.

**Comment by Envek** [comment]
Merged, thank you, it's awesome!

**Pull request merged**
